service: default
runtime: custom
instance_class: F2

env_variables:
  BACKEND_URL: "https://backend-dot-project-agentes.ue.r.appspot.com/query"

entrypoint: streamlit run app.py --server.port 8080 --server.enableCORS false --server.enableXsrfProtection false

automatic_scaling:
  min_instances: 0
  max_instances: 2
