service: default
runtime: custom
env: flex  # <-- Obligatorio para contenedores personalizados como Streamlit

env_variables:
  BACKEND_URL: "https://backend-dot-project-agentes.ue.r.appspot.com/query"

entrypoint: streamlit run app.py --server.port 8080 --server.enableCORS false --server.enableXsrfProtection false

automatic_scaling:
  min_num_instances: 1 # Flex requiere al menos 1 instancia
  max_num_instances: 2
  cpu_utilization:
    target_utilization: 0.75

# Añadimos un chequeo de salud para evitar timeouts durante el arranque
readiness_check:
  path: "/_stcore/health" # Streamlit tiene una ruta de salud integrada
  check_interval_sec: 30
  timeout_sec: 10
  failure_threshold: 10
  success_threshold: 2
  app_start_timeout_sec: 1800
