# contenido de frontend/app.yaml
service: default
runtime: custom
# La línea "env: flex" ha sido eliminada.

env_variables:
  BACKEND_URL: "https://backend-dot-project-agentes.sa-west1.r.appspot.com/query"

entrypoint: streamlit run app.py --server.port 8080 --server.enableCORS false --server.enableXsrfProtection false

automatic_scaling:
  min_instances: 0
  max_instances: 2
  target_cpu_utilization: 0.75
