service: default
runtime: custom
env: flex

env_variables:
  BACKEND_URL: "https://backend-dot-project-agentes.ue.r.appspot.com/query"

entrypoint: streamlit run app.py --server.port 8080 --server.enableCORS false --server.enableXsrfProtection false

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 2
  cpu_utilization:
    target_utilization: 0.75

# --- CONFIGURACIÓN DE CHEQUEO DE SALUD AJUSTADA A LÍMITES VÁLIDOS ---
readiness_check:
  path: "/_stcore/health"
  check_interval_sec: 60     # Comprueba cada 60 segundos
  timeout_sec: 4           # Tiempo de espera por respuesta
  failure_threshold: 10      # MÁXIMO permitido. 10 fallos * 60s = 10 minutos de margen.
  success_threshold: 2       # Necesita 2 respuestas OK para declararse saludable
  app_start_timeout_sec: 1800  # 30 minutos de tiempo total de arranque
