# En frontend/app.yaml
# --- CONFIGURACIÓN PARA APP ENGINE STANDARD CON DOCKER ---
service: default
runtime: custom # Necesario para usar Docker con Streamlit

env_variables:
  BACKEND_URL: "https://backend-dot-project-agentes.ue.r.appspot.com/query"

entrypoint: streamlit run app.py --server.port 8080 --server.enableCORS false --server.enableXsrfProtection false

# La sintaxis de escalado para Standard que SÍ permite cero instancias
automatic_scaling:
  min_instances: 0
  max_instances: 2
