# En frontend/app.yaml
service: default
runtime: custom
env: flex

env_variables:
  BACKEND_URL: "https://backend-dot-project-agentes.ue.r.appspot.com/query"

entrypoint: streamlit run app.py --server.port 8080 --server.enableCORS false --server.enableXsrfProtection false

automatic_scaling:
  min_num_instances: 1  # <-- La concesión necesaria para Flex
  max_num_instances: 2
  cpu_utilization:
    target_utilization: 0.75
