# Ruta: backend/app.yaml
service: backend
runtime: custom

secret_env_variables:
  GOOGLE_API_KEY:
    secret: "gemini-api-key"
    version: "latest"

entrypoint: uvicorn main:app --host 0.0.0.0 --port 8080

automatic_scaling:
  min_instances: 0
  max_instances: 1
  target_cpu_utilization: 0.75
