# En backend/app.yaml
# --- CONFIGURACIÓN NATIVA PARA APP ENGINE STANDARD ---
runtime: python312  # Usamos el runtime nativo de Python

# App Engine Standard SÍ soporta esta directiva
secret_env_variables:
  GOOGLE_API_KEY:
    secret: "gemini-api-key"
    version: "latest"

# El entrypoint para runtimes nativos usa gunicorn
entrypoint: gunicorn -b :$PORT main:app

# La sintaxis de escalado para Standard que SÍ permite cero instancias
automatic_scaling:
  min_instances: 0
  max_instances: 1
