# backend/app.yaml
service: backend
runtime: custom
env: flex

# El entrypoint anula el CMD del Dockerfile y es la forma recomendada
# para App Engine. Usará el puerto 8080 internamente.
entrypoint: uvicorn main:app --host 0.0.0.0 --port 8080

automatic_scaling:
  min_num_instances: 0
  max_num_instances: 1
  cpu_utilization:
    target_utilization: 0.65
