# En backend/app.yaml
service: backend
runtime: custom
env: flex

entrypoint: uvicorn main:app --host 0.0.0.0 --port 8080

automatic_scaling:
  min_num_instances: 1  # <-- La concesión necesaria para Flex
  max_num_instances: 2
  cpu_utilization:
    target_utilization: 0.75
