# En backend/app.yaml
service: backend
runtime: custom
env: flex  # <-- AÑADE ESTA LÍNEA

entrypoint: uvicorn main:app --host 0.0.0.0 --port 8080

automatic_scaling:
  min_instances: 0
  max_instances: 1
  cpu_utilization: 0.75
