# Ruta: backend/app.yaml
# --- VERSIÓN FINAL CON MÁS MEMORIA ---
service: backend
runtime: python311
instance_class: F4  # Aumentamos la memoria a 1024MB

entrypoint: gunicorn -b :$PORT main:app -w 4 -k uvicorn.workers.UvicornWorker

automatic_scaling:
  min_instances: 0
  max_instances: 1
