# Ruta: backend/app.yaml
# --- VERSIÓN FINAL OPTIMIZADA ---
service: backend
runtime: python311

# Usamos la instancia más potente disponible para escalado automático
instance_class: B8

# --- OPTIMIZACIÓN CLAVE ---
# Reducimos el número de workers a 1 para minimizar el consumo de memoria.
# Aumentamos el timeout para darle tiempo a arrancar.
entrypoint: gunicorn -b :$PORT main:app -w 1 --timeout 300 -k uvicorn.workers.UvicornWorker

automatic_scaling:
  min_instances: 0
  max_instances: 1
