# Ruta: backend/app.yaml
# --- VERSIÓN FINAL CON 4GB DE MEMORIA ---
service: backend
runtime: python311
instance_class: B16  # Aumentamos la memoria a 4096MB

entrypoint: gunicorn -b :$PORT main:app -w 4 -k uvicorn.workers.UvicornWorker

automatic_scaling:
  min_instances: 0
  max_instances: 1
