# backend/app.yaml
service: backend
runtime: custom
env: flex

# Esta sección le dice a App Engine que obtenga el secreto llamado 'gemini-api-key'
# y lo inyecte en el entorno de ejecución como la variable 'GOOGLE_API_KEY'.
secret_env_variables:
  GOOGLE_API_KEY:
    secret: "gemini-api-key"
    version: "latest" # Siempre usará la última versión del secreto

entrypoint: uvicorn main.app --host 0.0.0.0 --port 8080

automatic_scaling:
  min_num_instances: 0
  max_num_instances: 1
  cpu_utilization:
    target_utilization: 0.65
